### ISSUE TITLE
Laravel v7+ Support

### ISSUE THREAD

**Issue by DevynCJohnson** [imajkumar/laravel-theme-management#2]
Your software is amazing. I thank you for your work.

However, I am needing to update my project to Laravel v7.12. However, your Laravel plugin/package does not support Laravel v7.12. Your software is amazing and I do not want to have to go through Imajkumar-Laravel-Theme withdrawal nor have to find an alternative.

**Comment by C0kkie** [comment]
Its supporting laravel 7? Not sure why you opened the issue here again, while you also opened it in the old package? Did you even try this package here?

**Comment by DevynCJohnson** [comment]
True, I have not tested your version yet. Although, I read on the main page (i.e. the README.md file) that you guarantee support for Laravel v6.3. As for posting here and the original package, I first posted on the original package and the developer informed me about your project.

**Comment by C0kkie** [comment]
You should test things befor you open issues

**Comment by DevynCJohnson** [comment]
Awesome, this works on Laravel v7.14. Thanks!
