### ISSUE TITLE
Laravel 8x - Call to undefined function Ayra\Theme\starts_with()

### ISSUE THREAD

**Issue by DerekBuntin** [imajkumar/laravel-theme-management#4]
The string helpers were upgraded since Laravel 6x so starts_with should now be Str::startsWith()

`vendor/ayra/laravel-themes/src/AssetContainer.php:95`

I realise you can use Laravel Helpers for this but would rather keep the packages minimal when the upgraded methods are available, can you update the package to work with Laravel 6x without the helpers?

**Comment by imajkumar** [comment]
Thanks updated 
now it is working with Laravel 10.x also
